name: Forms Flow web-components

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  setup-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  # linting:
  #   needs: setup-job
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Install dependencies
  #       run: |
  #         npm ci
  #     - name: Linting
  #       run: |
  #         npm run lint
#   unit-tests:
#     needs: setup-job
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18]

#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install dependencies
#         run: |
#           npm ci
#       - name: Unit Test
#         id: test
#         run: |
#           npm test a
  build-check:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci 
        working-directory: ./forms-flow-webcomponent
      - name: Build
        id: build
        run: |
          npm run build
        working-directory: ./forms-flow-webcomponent

